sprites.onOverlap(SpriteKind.Player, SpriteKind.Player, function (sprite, otherSprite) {
    Jelly1.startEffect(effects.rings, 100)
    Jelly2.startEffect(effects.rings, 100)
})
let Jelly2: Sprite = null
let Jelly1: Sprite = null
scene.setBackgroundImage(img`
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbddbbbbbbbbbdbbbbbbbbbbbbbbbbbbbbbbbbbbbbddbbbbbbbbbdbbbbbbbbbbbbbbbbbbbbbbbbbbbbddbbbbbbbbbdbbbbbbbbbbbbbbbbbbbbbbbbbbbbddbbbbbbbbbdbbbbbbbbbbbbbbbbbbbbbbbbb
    bdddbbbbbbbbbddbbbbbbbbbbbbbbbbbbbbbbbdbbdddbbbbbbbbbddbbbbbbbbbbbbbbbbbbbbbbbdbbdddbbbbbbbbbddbbbbbbbbbbbbbbbbbbbbbbbdbbdddbbbbbbbbbddbbbbbbbbbbbbbbbbbbbbbbb6b
    bbdbbddbbbddbbddbbbbddbbbbbbbbbbbbbbbbddbbdbbddbbbddbbddbbbbddbbbbbbbbbbbbbbbbddbbdbbddbbbddbbddbbbbddbbbbbbbbbbbbbbbbddbbdbbddbbbddbbddbbbbddbbbbbbbbbbbbbbbb66
    ddddddbbdbbddbddbbdbddbbbbbbbbbbbbbbdd7dddddddbbdbbddbddbbdbddbbbbbbbbbbbbbbdd7dddddddbbdbbddbddbbdbddbbbbbbbbbbbbbbdd7dddddddbbdbbddbddbbdbddbbbbbbbbbbbbbbdd76
    dddddbbbddbdddddbddddbbbbbbbbbbbbbdddd77dddddbbbddbdddddbddddbbbbbbbbbbbbbdddd77dddddbbbddbdddddbddddbbbbbbbbbbbbbdddd77dddddbbbddbdddddbddddbbbbbbbbbbbbbdddd77
    dddddbdddddddd7dddddbbbdbbbbbbdddbbbddd7dddddbdddddddd7dddddbbbdbbbbbbdddbbbddd7dddddbdddddddd7dddddbbbdbbbbbbdddbbbddd7dddddbdddddddd7dddddbbbdbbbbbbdddbbbddd7
    ddddddddddddd77dd77dddddbbdddbbbddbbbdddddddddddddddd77dd77dddddbbdddbbbddbbbdddddddddddddddd77dd77dddddbbdddbbbddbbbdddddddddddddddd77dd77dddddbbdddbbbddbbbddd
    ddddddddddddd7dddd77dddbbd77ddbbddddddddddddddddddddd7dddd77dddbbd77ddbbddddddddddddddddddddd7dddd77dddbbd77ddbbddddddddddddddddddddd7dddd77dddbbd77ddbbdddddddd
    ddcddddddddddddddddddddbdd777ddbddddddddddcddddddddddddddddddddbdd777ddbddddddddddcddddddddddddddddddddbdd777ddbddddddddddcddddddddddddddddddddbdd777ddbdddddddd
    ddcddddddddddddddddddddddc677dddddddddddddcddddddddddddddddddddddc677dddddddddddddcddddddddddddddddddddddc677dddddddddddddcddddddddddddddddddddddc677ddddddddddd
    ddcddddddddddddddddddddddcc67dddddddddddddcddddddddddddddddddddddcc67dddddddddddddcddddddddddddddddddddddcc67dddddddddddddcddddddddddddddddddddddcc67ddddddddddd
    ddcdddddddaccddddddddaaddcccddddddddddddddcdddddddaccddddddddaaddcccddddddddddddddcdddddddaccddddddddaaddcccddddddddddddddcdddddddaccddddddddaaddcccdddddddddddd
    ddcddddddaadccddddddccadddccddddddddddddddcddddddaaaccddddddaaadddccddddddddddddddcddddddaaaccddddddaaadddccddddddddddddddcddddddaaaccddddddaaadddccdddddddddddd
    dccddd9ddaa66cccdadddcaaddccdddddddddddddccdddaddaa66cccdadddcaaddccdddddddddddddccdddaddaa66cccdadddcaaddccdddddddddddddccdddaddaa66cccdadddcaaddccdddddddddddd
    dccdddcadda6dacccaaddcaaddcccddddddddddddccdddcadda6dacccaaddcaaddcccddddddddddddccdddcadda6dacccaaddcaaddcccddddddddddddccdddcadda6dacccaaddcaaddcccddddddddddd
    dccddccaaaacaa6ccaacccaddddccddddddddddddccddccaaaacaa6ccaacccaddddccddddddddddddccddccaaaacaa6ccaacccaddddccddddddddddddccddccaaaacaa6ccaacccaddddccddddddddddd
    cccdddcaaaacaa6ccaaccaaddadcccddadddddddcccdddcaaaacaa6ccaaccaaddadcccddadddddddcccdddcaaaacaa6ccaaccaaddadcccddadddddddcccdddcaaaacaa6ccaaccaaddadcccddcddddddd
    cccccdcaaaacaaacccaccaaaaa6cccddaaadddddcccccdcaaaacaaacccaccaaaaa6cccddaaadddddcccccdcaaaacaaacccaccaaaaa6cccddaaadddddcccccdcaaaacaaacccaccaaaaa6cccddcccddddd
    ccc6cccaaaacaaaaccaccaaaac6cccadaaddddddccc6cccaaaacaaaaccaccaaaac6cccadaaddddddccc6cccaaaacaaaaccaccaaaac6cccadaaddddddccc6cccaaaacaaaaccaccaaaac6ccccdccdddddd
    ccc6cccaaacaaaaacccccaaaacacccaaaaddaaddccc6cccaaacaaaaacccccaaaacacccaaaaddaaddccc6cccaaacaaaaacccccaaaacacccaaaaddaaddccc6cccaaacaaaaacccccaaaacacccccccddaadd
    cccccccaaacaaaaaaccccaaaacaccccaaaacaaadcccccccaaacaaaaaaccccaaaacaccccaaaacaaadcccccccaaacaaaaaaccccaaaacaccccaaaacaaadcccccccaaacaaaaaaccccaaaacacccccccccaaad
    ccaccccaaccaaaaaaaccaaaaccaccccaaaacaaaaccaccccaaccaaaaaaaccaaaaccaccccaaaacaaaaccaccccaaccaaaaaaaccaaaaccaccccaaaacaaaaccaccccaaccaaaaaaaccaaaaccacccccccccaaaa
    ccaacccccaaaaaaaaacccaaacaaacccaaaacaaaaccaacccccaaaaaaaaacccaaacaaacccaaaacaaaaccaacccccaaaaaaaaacccaaacaaacccaaaacaaaaccaacccccaaaaaaaaacccaaacaaaccccccccaaaa
    ccaaccccaaaaaaaaaacccccccaaacccaaaacaaacccaaccccaaaaaaaaaacccccccaaacccaaaacaaacccaaccccaaaaaaaaaacccccccaaacccaaaacaaacccaaccccaaaaaaaaaacccccccaaaccccccccaaac
    ccaacccaaaaaaaaaaaccccccaaaaccccaaacaaacccaacccaaaaaaaaaaaccccccaaaaccccaaacaaacccaacccaaaaaaaaaaaccccccaaaaccccaaacaaacccaacccaaaaaaaaaaaccccccaaaaccccccccaaac
    ccaacccaaaaaaaaaaaccccccccaaccccaaacaaacccaacccaaaaaaaaaaaccccccccaaccccaaacaaacccaacccaaaaaaaaaaaccccccccaaccccaaacaaacccaacccaaaaaaaaaaaccccccccaaccccccccaaac
    caaaaccaaaaaaaaaaccccccccccccccccaaacaaccaaaaccaaaaaaaaaaccccccccccccccccaaacaaccaaaaccaaaaaaaaaaccccccccccccccccaaacaaccaaaaccaaaaaaaaaaccccccccccccccccccccaac
    caaaacccaaaaaaaaaccaaaaacccccccccaaacaaccaaaacccaaaaaaaaaccaaaaacccccccccaaacaaccaaaacccaaaaaaaaaccaaaaacccccccccaaacaaccaaaacccaaaaaaaaaccaaaaacccccccccccccaac
    caaaaccccaaaaaaaaccaaaaaaccccccccaaacacccaaaaccccaaaaaaaaccaaaaaaccccccccaaacacccaaaaccccaaaaaaaaccaaaaaaccccccccaaacacccaaaaccccaaaaaaaaccaaaaaaccccccccccccacc
    caaaacccccaaaaaacccaaaaaaacccccccaaacccccaaaacccccaaaaaacccaaaaaaacccccccaaacccccaaaacccccaaaaaacccaaaaaaacccccccaaacccccaaaacccccaaaaaacccaaaaaaacccccccccccccc
    ccaaaaacccccaaaacccaaaaaaaaacccccaaaccccccaaaaacccccaaaacccaaaaaaaaacccccaaaccccccaaaaacccccaaaacccaaaaaaaaacccccaaaccccccaaaaacccccaaaacccaaaaaaaaacccccccccccc
    acaaaaacccccccacccaaaaaaaaaacccccaaccccaacaaaaacccccccacccaaaaaaaaaacccccaaccccaacaaaaacccccccacccaaaaaaaaaacccccaaccccaacaaaaacccccccacccaaaaaaaaaaccccccccccca
    acaaaaaaccccccccccaaaaaaaaaacccccaacccaaacaaaaaaccccccccccaaaaaaaaaacccccaacccaaacaaaaaaccccccccccaaaaaaaaaacccccaacccaaacaaaaaaccccccccccaaaaaaaaaaccccccccccaa
    acaaaaaacccccccccaaaaaaaaaaacccccaaccaaaacaaaaaacccccccccaaaaaaaaaaacccccaaccaaaacaaaaaacccccccccaaaaaaaaaaacccccaaccaaaacaaaaaacccccccccaaaaaaaaaaacccccccccaaa
    accaaaaacccccccaaaaaaaaaaaaacccccaacccaaaccaaaaacccccccaaaaaaaaaaaaacccccaacccaaaccaaaaacccccccaaaaaaaaaaaaacccccaacccaaaccaaaaacccccccaaaaaaaaaaaaaccccccccccaa
    aaccaaaaccccccaaaaaaaaaaaaaacccccaacccaaaaccaaaaccccccaaaaaaaaaaaaaacccccaacccaaaaccaaaaccccccaaaaaaaaaaaaaacccccaacccaaaaccaaaaccccccaaaaaaaaaaaaaaccccccccccaa
    aacccaaaccccccaaaaaaaaaaaaaacccccacccccaaacccaaaccccccaaaaaaaaaaaaaacccccacccccaaacccaaaccccccaaaaaaaaaaaaaacccccacccccaaacccaaaccccccaaaaaaaaaaaaaaccccccccccca
    aaaaccccccccccaaaaaaaaaaaaaccccccacccacaaaaaccccccccccaaaaaaaaaaaaaccccccacccacaaaaaccccccccccaaaaaaaaaaaaaccccccacccacaaaaaccccccccccaaaaaaaaaaaaaccccccccccaca
    aaaaccccccccccaaaaaaaaaaaaacccccccccaacaaaaaccccccccccaaaaaaaaaaaaacccccccccaacaaaaaccccccccccaaaaaaaaaaaaacccccccccaacaaaaaccccccccccaaaaaaaaaaaaacccccccccaaca
    aaaaaaccccccccaaaaaaaaaaaaacccccccccaaccaaaaaaccccccccaaaaaaaaaaaaacccccccccaaccaaaaaaccccccccaaaaaaaaaaaaacccccccccaaccaaaaaaccccccccaaaaaaaaaaaaacccccccccaacc
    caaaaaaaccccccaaaaaaaaaaaacccccccccaaaaccaaaaaaaccccccaaaaaaaaaaaacccccccccaaaaccaaaaaaaccccccaaaaaaaaaaaacccccccccaaaaccaaaaaaaccccccaaaaaaaaaaaacccccccccaaaac
    ccaaaaaaacccccaaaaaaaaaaaacccccccccaaaaaccaaaaaaacccccaaaaaaaaaaaacccccccccaaaaaccaaaaaaacccccaaaaaaaaaaaacccccccccaaaaaccaaaaaaacccccaaaaaaaaaaaacccccccccaaaaa
    ccaaaaaaacccccaaaaaaaaaaaaccccccccaaaaaaccaaaaaaacccccaaaaaaaaaaaaccccccccaaaaaaccaaaaaaacccccaaaaaaaaaaaaccccccccaaaaaaccaaaaaaacccccaaaaaaaaaaaaccccccccaaaaaa
    acaaaaaaacccccaaaaaaaaaaacccccccccaaaaaaacaaaaaaacccccaaaaaaaaaaacccccccccaaaaaaacaaaaaaacccccaaaaaaaaaaacccccccccaaaaaaacaaaaaaacccccaaaaaaaaaaacccccccccaaaaaa
    acaaaaaaacccccaaaaaaaaaaacccccccccaaaaaaacaaaaaaacccccaaaaaaaaaaacccccccccaaaaaaacaaaaaaacccccaaaaaaaaaaacccccccccaaaaaaacaaaaaaacccccaaaaaaaaaaacccccccccaaaaaa
    acaaaaaaacccccaaaaaaaaaaacccccccccaaaaaaacaaaaaaacccccaaaaaaaaaaacccccccccaaaaaaacaaaaaaacccccaaaaaaaaaaacccccccccaaaaaaacaaaaaaacccccaaaaaaaaaaacccccccccaaaaaa
    acaaaaaaacccccaaaaaaaaaaacccccccccaaaaaaacaaaaaaacccccaaaaaaaaaaacccccccccaaaaaaacaaaaaaacccccaaaaaaaaaaacccccccccaaaaaaacaaaaaaacccccaaaaaaaaaaacccccccccaaaaaa
    accaaaaaacccccaaaaaaaaaaaccccccccaaaaaaaaccaaaaaacccccaaaaaaaaaaaccccccccaaaaaaaaccaaaaaacccccaaaaaaaaaaaccccccccaaaaaaaaccaaaaaacccccaaaaaaaaaaaccccccccaaaaaaa
    accaaaaaacccccaaaaaaaaaaaccccccccaaaaaaaaccaaaaaacccccaaaaaaaaaaaccccccccaaaaaaaaccaaaaaacccccaaaaaaaaaaaccccccccaaaaaaaaccaaaaaacccccaaaaaaaaaaaccccccccaaaaaaa
    cccaaaaaacccccaaaaaaaaaaaccccccccaaaaaaacccaaaaaacccccaaaaaaaaaaaccccccccaaaaaaacccaaaaaacccccaaaaaaaaaaaccccccccaaaaaaacccaaaaaacccccaaaaaaaaaaaccccccccaaaaaaa
    ccaaaaaaacccccaaaaaaaaaaaccccccccaaaaaaaccaaaaaaacccccaaaaaaaaaaaccccccccaaaaaaaccaaaaaaacccccaaaaaaaaaaaccccccccaaaaaaaccaaaaaaacccccaaaaaaaaaaaccccccccaaaaaaa
    ccaaaaaaaccccccaaaaaaaaaaccccccccaaaaaaaccaaaaaaaccccccaaaaaaaaaaccccccccaaaaaaaccaaaaaaaccccccaaaaaaaaaaccccccccaaaaaaaccaaaaaaaccccccaaaaaaaaaaccccccccaaaaaaa
    ccaaaaaaaccccccaaaaaaaaaaccccccccaaaaaaaccaaaaaaaccccccaaaaaaaaaaccccccccaaaaaaaccaaaaaaaccccccaaaaaaaaaaccccccccaaaaaaaccaaaaaaaccccccaaaaaaaaaaccccccccaaaaaaa
    ccaaaaaaaccccccaaaaaaaaaacccccccaaaaaaaaccaaaaaaaccccccaaaaaaaaaacccccccaaaaaaaaccaaaaaaaccccccaaaaaaaaaacccccccaaaaaaaaccaaaaaaaccccccaaaaaaaaaacccccccaaaaaaaa
    caaaaaaaaccccccaaaaaaaaaacccccccaaaaaaaccaaaaaaaaccccccaaaaaaaaaacccccccaaaaaaaccaaaaaaaaccccccaaaaaaaaaacccccccaaaaaaaccaaaaaaaaccccccaaaaaaaaaacccccccaaaaaaac
    caaaaaaaaccccccaaaaaaaaaacccccccaaaaaacccaaaaaaaaccccccaaaaaaaaaacccccccaaaaaacccaaaaaaaaccccccaaaaaaaaaacccccccaaaaaacccaaaaaaaaccccccaaaaaaaaaacccccccaaaaaacc
    caaaaaaaaccccccaaaaaaaaaacccccccaaaaaacccaaaaaaaaccccccaaaaaaaaaacccccccaaaaaacccaaaaaaaaccccccaaaaaaaaaacccccccaaaaaacccaaaaaaaaccccccaaaaaaaaaacccccccaaaaaacc
    aaaaaaaaacccccccaaaaaaaaacccccccaaaaacccaaaaaaaaacccccccaaaaaaaaacccccccaaaaacccaaaaaaaaacccccccaaaaaaaaacccccccaaaaacccaaaaaaaaacccccccaaaaaaaaacccccccaaaaaccc
    aaaaaaaaacccccccaaaaaaaaacccccccaaaaacccaaaaaaaaacccccccaaaaaaaaacccccccaaaaacccaaaaaaaaacccccccaaaaaaaaacccccccaaaaacccaaaaaaaaacccccccaaaaaaaaacccccccaaaaaccc
    aaaaaaaaacccccccaaaaaaaaacccccccaaaaacccaaaaaaaaacccccccaaaaaaaaacccccccaaaaacccaaaaaaaaacccccccaaaaaaaaacccccccaaaaacccaaaaaaaaacccccccaaaaaaaaacccccccaaaaaccc
    aaaaaaaaaccccccccaaaaaaaacccccccaaaaccccaaaaaaaaaccccccccaaaaaaaacccccccaaaaccccaaaaaaaaaccccccccaaaaaaaacccccccaaaaccccaaaaaaaaaccccccccaaaaaaaacccccccaaaacccc
    aaaaaaaaaccccccccaaaaaaaacccccccaaaaccccaaaaaaaaaccccccccaaaaaaaacccccccaaaaccccaaaaaaaaaccccccccaaaaaaaacccccccaaaaccccaaaaaaaaaccccccccaaaaaaaacccccccaaaacccc
    aaaaaaaaaccccccccaaaaaaaacccccccaaaacccaaaaaaaaaaccccccccaaaaaaaacccccccaaaacccaaaaaaaaaaccccccccaaaaaaaacccccccaaaacccaaaaaaaaaaccccccccaaaaaaaacccccccaaaacccc
    aaaaaaaaaaccccccccaaaaaaccccccccaaaacccaaaaaaaaaaaccccccccaaaaaaccccccccaaaacccaaaaaaaaaaaccccccccaaaaaaccccccccaaaacccaaaaaaaaaaaccccccccaaaaaaccccccccaaaacccc
    caaaaaaaaaccccccccaaaaaacccccccccccccccccaaaaaaaaaccccccccaaaaaacccccccccccccccccaaaaaaaaaccccccccaaaaaacccccccccccccccccaaaaaaaaaccccccccaaaaaacccccccccccccccc
    cccccaaaaaccccccccaaaaaacccccccccccccccccccccaaaaaccccccccaaaaaacccccccccccccccccccccaaaaaccccccccaaaaaacccccccccccccccccccccaaaaaccccccccaaaaaacccccccccccccccc
    ccccccccaacccccccccaaaccccccccccccccccccccccccccaacccccccccaaaccccccccccccccccccccccccccaacccccccccaaaccccccccccccccccccccccccccaacccccccccaaacccccccccccccccccc
    cccccccccccccccccccacccccccccccccccccccccccccccccccccccccccacccccccccccccccccccccccccccccccccccccccacccccccccccccccccccccccccccccccccccccccacccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccbbbbbbbbbbccccccccccccccccccccccccccccccbbbbbbbbbbccccccccccccccccccccccccccccccbbbbbbbbbbccccccccccccccccccccccccccccccbbbbbbbbbbccccccccccc
    ccccccccccccccbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbcccccc
    cccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbcccc
    ccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcc
    cccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    `)
effects.confetti.startScreenEffect()
Jelly1 = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . 2 2 2 2 2 . . . . . . 
    . . . . 2 a a a a a 2 . . . . . 
    . . . . 2 1 f a f 1 2 . . . . . 
    . . . . 2 a a a a a 2 . . . . . 
    . . . . 2 a a f a a 2 . . . . . 
    . . . 2 2 2 a a a 2 2 2 . . . . 
    . . . 2 a 2 2 2 2 2 a 2 . . . . 
    . . . 2 2 2 2 2 a 2 2 2 . . . . 
    . . . . . 2 a 2 2 2 . . . . . . 
    . . . . . 2 2 2 . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Player)
controller.player1.moveSprite(Jelly1)
Jelly2 = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . 8 8 8 8 8 8 8 . . . . 
    . . . . . 8 9 9 9 9 9 8 . . . . 
    . . . . . 8 f f 9 f f 8 . . . . 
    . . . . . 8 9 9 9 9 9 8 . . . . 
    . . . . . 8 9 9 f 9 9 8 . . . . 
    . . . . . 8 8 8 8 8 8 8 . . . . 
    . . . . . 8 . . 8 . . 8 . . . . 
    . . . . . . 8 . . 8 . . 8 . . . 
    . . . . . 8 . . 8 . . 8 . . . . 
    . . . . . . 8 . . 8 . . 8 . . . 
    . . . . . 8 . . 8 . . 8 . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Player)
controller.player2.moveSprite(Jelly2)
Jelly1.setPosition(16, 11)
Jelly2.setPosition(140, 96)
Jelly1.setStayInScreen(true)
Jelly2.setStayInScreen(true)
